version: '3.9'
services:
  backend:
    container_name: template-ts-api
    build:
      context: ./
      dockerfile: ./express/Dockerfile
    ports:
      - ${PORT_EXPRESS_DOCKER}:${PORT_EXPRESS}
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    networks:
      - sk3u4pp_network
    depends_on:
      - postgres
  ngnix:
    container_name: ngnix_api
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - ${PORT_NGINX_DOCKER}:443
    networks:
      - sk3u4pp_network
    depends_on:
      - backend
  postgres:
    container_name: template-ts-db
    image: "postgres:latest"
    restart: "always"
    ports:
      - ${PORT_DB_DOCKER}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - sk3u4pp_network
networks:
  sk3u4pp_network:
    driver: bridge
